// SPDX-FileCopyrightText: 2026 The Pion community <https://pion.ly>
// SPDX-License-Identifier: MIT

package turn

import (

	//nolint:gosec,gci

	"time"

	"github.com/pion/logging"
)

// GenerateLongTermCredentials can be used to create credentials valid for [duration] time.
func GenerateLongTermCredentials(sharedSecret string, duration time.Duration) (string, string, error) {
	_ = "STUB: not implemented"
	return "", "", nil
}

// GenerateLongTermTURNRESTCredentials can be used to create credentials valid for [duration] time.
func GenerateLongTermTURNRESTCredentials(sharedSecret string, user string, duration time.Duration) (
	string,
	string,
	error,
) {
	_ = "STUB: not implemented"
	return "", "", nil
}

func longTermCredentials(username string, sharedSecret string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Not sure if this will ever happen

// NewLongTermAuthHandler returns a turn.AuthAuthHandler used with Long Term (or Time Windowed) Credentials.
// See: https://datatracker.ietf.org/doc/html/rfc8489#section-9.2
// .
func NewLongTermAuthHandler(sharedSecret string, logger logging.LeveledLogger) AuthHandler {
	_ = "STUB: not implemented"
	return *new(AuthHandler)
}

// LongTermTURNRESTAuthHandler returns a turn.AuthAuthHandler that can be used to authenticate
// time-windowed ephemeral credentials generated by the TURN REST API as described in
// https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00
//
// The supported format of is timestamp:username, where username is an arbitrary user id and the
// timestamp specifies the expiry of the credential.
func LongTermTURNRESTAuthHandler(sharedSecret string, logger logging.LeveledLogger) AuthHandler {
	_ = "STUB: not implemented"
	return *new(AuthHandler)
}

// Parse timestamp and userID. Set userID to the full username if the id cannot be
// parsed.
